# Auto-generated base PS7 (processing_system7 v5.5) configuration.
# Source: ARM/ARM/arm_13_lwip design_1.bd  (Vivado 2024.2, xc7z020clg400-2)
# Board memory: DDR3 MT41J256M16 RE-125, 16-bit, 533.333 MHz  ->  512 MB @ 0x0010_0000..0x1FFF_FFFF
# DDR3 + Ethernet(GEM0/RGMII+MDIO) + UART1 console are configured here.
# QSPI / SD0(microSD) / SD1(eMMC) / M_AXI_GP0 / FCLK_CLK0 are added in create_bd.tcl.
#
# 344 parameters

set PS7_BASE_CONFIG [list \
    CONFIG.PCW_APU_CLK_RATIO_ENABLE 6:2:1 \
    CONFIG.PCW_APU_PERIPHERAL_FREQMHZ 666.666666 \
    CONFIG.PCW_CAN0_PERIPHERAL_CLKSRC External \
    CONFIG.PCW_CAN0_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_CAN1_PERIPHERAL_CLKSRC External \
    CONFIG.PCW_CAN1_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_CAN_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_CLK0_FREQ 10000000 \
    CONFIG.PCW_CLK1_FREQ 10000000 \
    CONFIG.PCW_CLK2_FREQ 10000000 \
    CONFIG.PCW_CLK3_FREQ 10000000 \
    CONFIG.PCW_CPU_CPU_6X4X_MAX_RANGE 767 \
    CONFIG.PCW_CPU_PERIPHERAL_CLKSRC {ARM PLL} \
    CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ 33.333333 \
    CONFIG.PCW_DCI_PERIPHERAL_CLKSRC {DDR PLL} \
    CONFIG.PCW_DCI_PERIPHERAL_FREQMHZ 10.159 \
    CONFIG.PCW_DDR_PERIPHERAL_CLKSRC {DDR PLL} \
    CONFIG.PCW_DDR_RAM_BASEADDR 0x00100000 \
    CONFIG.PCW_DDR_RAM_HIGHADDR 0x1FFFFFFF \
    CONFIG.PCW_DM_WIDTH 4 \
    CONFIG.PCW_DQS_WIDTH 4 \
    CONFIG.PCW_DQ_WIDTH 32 \
    CONFIG.PCW_ENET0_BASEADDR 0xE000B000 \
    CONFIG.PCW_ENET0_ENET0_IO {MIO 16 .. 27} \
    CONFIG.PCW_ENET0_GRP_MDIO_ENABLE 1 \
    CONFIG.PCW_ENET0_GRP_MDIO_IO {MIO 52 .. 53} \
    CONFIG.PCW_ENET0_HIGHADDR 0xE000BFFF \
    CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_ENET0_PERIPHERAL_ENABLE 1 \
    CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
    CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_ENET1_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_ENET_RESET_POLARITY {Active Low} \
    CONFIG.PCW_EN_4K_TIMER 0 \
    CONFIG.PCW_EN_CAN0 0 \
    CONFIG.PCW_EN_CAN1 0 \
    CONFIG.PCW_EN_CLK1_PORT 0 \
    CONFIG.PCW_EN_CLK2_PORT 0 \
    CONFIG.PCW_EN_CLK3_PORT 0 \
    CONFIG.PCW_EN_CLKTRIG0_PORT 0 \
    CONFIG.PCW_EN_CLKTRIG1_PORT 0 \
    CONFIG.PCW_EN_CLKTRIG2_PORT 0 \
    CONFIG.PCW_EN_CLKTRIG3_PORT 0 \
    CONFIG.PCW_EN_DDR 1 \
    CONFIG.PCW_EN_EMIO_CAN0 0 \
    CONFIG.PCW_EN_EMIO_CAN1 0 \
    CONFIG.PCW_EN_EMIO_ENET0 0 \
    CONFIG.PCW_EN_EMIO_ENET1 0 \
    CONFIG.PCW_EN_EMIO_GPIO 0 \
    CONFIG.PCW_EN_EMIO_I2C0 0 \
    CONFIG.PCW_EN_EMIO_I2C1 0 \
    CONFIG.PCW_EN_EMIO_MODEM_UART0 0 \
    CONFIG.PCW_EN_EMIO_MODEM_UART1 0 \
    CONFIG.PCW_EN_EMIO_PJTAG 0 \
    CONFIG.PCW_EN_EMIO_SPI0 0 \
    CONFIG.PCW_EN_EMIO_SPI1 0 \
    CONFIG.PCW_EN_EMIO_SRAM_INT 0 \
    CONFIG.PCW_EN_EMIO_TRACE 0 \
    CONFIG.PCW_EN_EMIO_TTC0 0 \
    CONFIG.PCW_EN_EMIO_TTC1 0 \
    CONFIG.PCW_EN_EMIO_UART0 0 \
    CONFIG.PCW_EN_EMIO_UART1 0 \
    CONFIG.PCW_EN_EMIO_WDT 0 \
    CONFIG.PCW_EN_ENET0 1 \
    CONFIG.PCW_EN_ENET1 0 \
    CONFIG.PCW_EN_GPIO 0 \
    CONFIG.PCW_EN_I2C0 0 \
    CONFIG.PCW_EN_I2C1 0 \
    CONFIG.PCW_EN_MODEM_UART0 0 \
    CONFIG.PCW_EN_MODEM_UART1 0 \
    CONFIG.PCW_EN_PJTAG 0 \
    CONFIG.PCW_EN_PTP_ENET0 0 \
    CONFIG.PCW_EN_PTP_ENET1 0 \
    CONFIG.PCW_EN_RST0_PORT 0 \
    CONFIG.PCW_EN_RST1_PORT 0 \
    CONFIG.PCW_EN_RST2_PORT 0 \
    CONFIG.PCW_EN_RST3_PORT 0 \
    CONFIG.PCW_EN_SPI0 0 \
    CONFIG.PCW_EN_SPI1 0 \
    CONFIG.PCW_EN_TRACE 0 \
    CONFIG.PCW_EN_TTC0 0 \
    CONFIG.PCW_EN_TTC1 0 \
    CONFIG.PCW_EN_UART0 0 \
    CONFIG.PCW_EN_UART1 1 \
    CONFIG.PCW_EN_USB0 0 \
    CONFIG.PCW_EN_USB1 0 \
    CONFIG.PCW_EN_WDT 0 \
    CONFIG.PCW_FCLK0_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK1_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK2_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK3_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ 50 \
    CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ 50 \
    CONFIG.PCW_FPGA3_PERIPHERAL_FREQMHZ 50 \
    CONFIG.PCW_GP0_EN_MODIFIABLE_TXN 1 \
    CONFIG.PCW_GP0_NUM_READ_THREADS 4 \
    CONFIG.PCW_GP0_NUM_WRITE_THREADS 4 \
    CONFIG.PCW_GP1_EN_MODIFIABLE_TXN 1 \
    CONFIG.PCW_GP1_NUM_READ_THREADS 4 \
    CONFIG.PCW_GP1_NUM_WRITE_THREADS 4 \
    CONFIG.PCW_GPIO_EMIO_GPIO_ENABLE 0 \
    CONFIG.PCW_GPIO_MIO_GPIO_ENABLE 0 \
    CONFIG.PCW_GPIO_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_I2C0_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_I2C1_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_I2C_RESET_POLARITY {Active Low} \
    CONFIG.PCW_IMPORT_BOARD_PRESET None \
    CONFIG.PCW_INCLUDE_ACP_TRANS_CHECK 0 \
    CONFIG.PCW_MIO_16_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_16_PULLUP enabled \
    CONFIG.PCW_MIO_16_SLEW fast \
    CONFIG.PCW_MIO_17_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_17_PULLUP enabled \
    CONFIG.PCW_MIO_17_SLEW fast \
    CONFIG.PCW_MIO_18_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_18_PULLUP enabled \
    CONFIG.PCW_MIO_18_SLEW fast \
    CONFIG.PCW_MIO_19_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_19_PULLUP enabled \
    CONFIG.PCW_MIO_19_SLEW fast \
    CONFIG.PCW_MIO_20_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_20_PULLUP enabled \
    CONFIG.PCW_MIO_20_SLEW fast \
    CONFIG.PCW_MIO_21_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_21_PULLUP enabled \
    CONFIG.PCW_MIO_21_SLEW fast \
    CONFIG.PCW_MIO_22_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_22_PULLUP enabled \
    CONFIG.PCW_MIO_22_SLEW fast \
    CONFIG.PCW_MIO_23_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_23_PULLUP enabled \
    CONFIG.PCW_MIO_23_SLEW fast \
    CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_24_PULLUP enabled \
    CONFIG.PCW_MIO_24_SLEW fast \
    CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_25_PULLUP enabled \
    CONFIG.PCW_MIO_25_SLEW fast \
    CONFIG.PCW_MIO_26_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_26_PULLUP enabled \
    CONFIG.PCW_MIO_26_SLEW fast \
    CONFIG.PCW_MIO_27_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_27_PULLUP enabled \
    CONFIG.PCW_MIO_27_SLEW fast \
    CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_48_PULLUP enabled \
    CONFIG.PCW_MIO_48_SLEW slow \
    CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_49_PULLUP enabled \
    CONFIG.PCW_MIO_49_SLEW slow \
    CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_52_PULLUP enabled \
    CONFIG.PCW_MIO_52_SLEW slow \
    CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_53_PULLUP enabled \
    CONFIG.PCW_MIO_53_SLEW slow \
    CONFIG.PCW_MIO_PRIMITIVE 54 \
    CONFIG.PCW_NAND_CYCLES_T_AR 1 \
    CONFIG.PCW_NAND_CYCLES_T_CLR 1 \
    CONFIG.PCW_NAND_CYCLES_T_RC 11 \
    CONFIG.PCW_NAND_CYCLES_T_REA 1 \
    CONFIG.PCW_NAND_CYCLES_T_RR 1 \
    CONFIG.PCW_NAND_CYCLES_T_WC 11 \
    CONFIG.PCW_NAND_CYCLES_T_WP 1 \
    CONFIG.PCW_NAND_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_NOR_CS0_T_CEOE 1 \
    CONFIG.PCW_NOR_CS0_T_PC 1 \
    CONFIG.PCW_NOR_CS0_T_RC 11 \
    CONFIG.PCW_NOR_CS0_T_TR 1 \
    CONFIG.PCW_NOR_CS0_T_WC 11 \
    CONFIG.PCW_NOR_CS0_T_WP 1 \
    CONFIG.PCW_NOR_CS0_WE_TIME 0 \
    CONFIG.PCW_NOR_CS1_T_CEOE 1 \
    CONFIG.PCW_NOR_CS1_T_PC 1 \
    CONFIG.PCW_NOR_CS1_T_RC 11 \
    CONFIG.PCW_NOR_CS1_T_TR 1 \
    CONFIG.PCW_NOR_CS1_T_WC 11 \
    CONFIG.PCW_NOR_CS1_T_WP 1 \
    CONFIG.PCW_NOR_CS1_WE_TIME 0 \
    CONFIG.PCW_NOR_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_NOR_SRAM_CS0_T_CEOE 1 \
    CONFIG.PCW_NOR_SRAM_CS0_T_PC 1 \
    CONFIG.PCW_NOR_SRAM_CS0_T_RC 11 \
    CONFIG.PCW_NOR_SRAM_CS0_T_TR 1 \
    CONFIG.PCW_NOR_SRAM_CS0_T_WC 11 \
    CONFIG.PCW_NOR_SRAM_CS0_T_WP 1 \
    CONFIG.PCW_NOR_SRAM_CS0_WE_TIME 0 \
    CONFIG.PCW_NOR_SRAM_CS1_T_CEOE 1 \
    CONFIG.PCW_NOR_SRAM_CS1_T_PC 1 \
    CONFIG.PCW_NOR_SRAM_CS1_T_RC 11 \
    CONFIG.PCW_NOR_SRAM_CS1_T_TR 1 \
    CONFIG.PCW_NOR_SRAM_CS1_T_WC 11 \
    CONFIG.PCW_NOR_SRAM_CS1_T_WP 1 \
    CONFIG.PCW_NOR_SRAM_CS1_WE_TIME 0 \
    CONFIG.PCW_OVERRIDE_BASIC_CLOCK 0 \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY0 0.080 \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY1 0.063 \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY2 0.057 \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY3 0.068 \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 -0.047 \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 -0.025 \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 -0.006 \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 -0.017 \
    CONFIG.PCW_PACKAGE_NAME clg400 \
    CONFIG.PCW_PCAP_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_PCAP_PERIPHERAL_FREQMHZ 200 \
    CONFIG.PCW_PERIPHERAL_BOARD_PRESET None \
    CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_PLL_BYPASSMODE_ENABLE 0 \
    CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} \
    CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
    CONFIG.PCW_PS7_SI_REV PRODUCTION \
    CONFIG.PCW_SDIO_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_SMC_CYCLE_T0 NA \
    CONFIG.PCW_SMC_CYCLE_T1 NA \
    CONFIG.PCW_SMC_CYCLE_T2 NA \
    CONFIG.PCW_SMC_CYCLE_T3 NA \
    CONFIG.PCW_SMC_CYCLE_T4 NA \
    CONFIG.PCW_SMC_CYCLE_T5 NA \
    CONFIG.PCW_SMC_CYCLE_T6 NA \
    CONFIG.PCW_SMC_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_SPI0_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_SPI1_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_SPI_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_TPIU_PERIPHERAL_CLKSRC External \
    CONFIG.PCW_TRACE_INTERNAL_WIDTH 2 \
    CONFIG.PCW_TRACE_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_TTC0_CLK0_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_TTC0_CLK0_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_TTC0_CLK1_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_TTC0_CLK1_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_TTC0_CLK2_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_TTC0_CLK2_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_TTC0_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_TTC1_CLK0_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_TTC1_CLK0_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_TTC1_CLK1_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_TTC1_CLK1_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_TTC1_CLK2_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_TTC1_CLK2_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_TTC1_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_UART0_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_UART1_BASEADDR 0xE0001000 \
    CONFIG.PCW_UART1_BAUD_RATE 115200 \
    CONFIG.PCW_UART1_GRP_FULL_ENABLE 0 \
    CONFIG.PCW_UART1_HIGHADDR 0xE0001FFF \
    CONFIG.PCW_UART1_PERIPHERAL_ENABLE 1 \
    CONFIG.PCW_UART1_UART1_IO {MIO 48 .. 49} \
    CONFIG.PCW_UART_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_UART_PERIPHERAL_FREQMHZ 100 \
    CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ 533.333374 \
    CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE 0 \
    CONFIG.PCW_UIPARAM_DDR_AL 0 \
    CONFIG.PCW_UIPARAM_DDR_BL 8 \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 0.25 \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 0.25 \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 0.25 \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 0.25 \
    CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {16 Bit} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH 54.563 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH 54.563 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH 54.563 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH 54.563 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN 0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH 101.239 \
    CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH 79.5025 \
    CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH 60.536 \
    CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH 71.7715 \
    CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 0.0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 0.0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 0.0 \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 0.0 \
    CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH 104.5365 \
    CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH 70.676 \
    CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH 59.1615 \
    CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM 0 \
    CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH 81.319 \
    CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY 160 \
    CONFIG.PCW_UIPARAM_DDR_ECC Disabled \
    CONFIG.PCW_UIPARAM_DDR_ENABLE 1 \
    CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ 533.333333 \
    CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP {Normal (0-85)} \
    CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} \
    CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41J256M16 RE-125} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE 1 \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE 1 \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL 1 \
    CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF 0 \
    CONFIG.PCW_UIPARAM_GENERATE_SUMMARY NA \
    CONFIG.PCW_USB0_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_USB1_PERIPHERAL_ENABLE 0 \
    CONFIG.PCW_USB_RESET_POLARITY {Active Low} \
    CONFIG.PCW_USE_AXI_FABRIC_IDLE 0 \
    CONFIG.PCW_USE_AXI_NONSECURE 0 \
    CONFIG.PCW_USE_CORESIGHT 0 \
    CONFIG.PCW_USE_CROSS_TRIGGER 0 \
    CONFIG.PCW_USE_CR_FABRIC 1 \
    CONFIG.PCW_USE_DDR_BYPASS 0 \
    CONFIG.PCW_USE_DEBUG 0 \
    CONFIG.PCW_USE_DMA0 0 \
    CONFIG.PCW_USE_DMA1 0 \
    CONFIG.PCW_USE_DMA2 0 \
    CONFIG.PCW_USE_DMA3 0 \
    CONFIG.PCW_USE_EXPANDED_IOP 0 \
    CONFIG.PCW_USE_FABRIC_INTERRUPT 0 \
    CONFIG.PCW_USE_HIGH_OCM 0 \
    CONFIG.PCW_USE_M_AXI_GP1 0 \
    CONFIG.PCW_USE_PROC_EVENT_BUS 0 \
    CONFIG.PCW_USE_PS_SLCR_REGISTERS 0 \
    CONFIG.PCW_USE_S_AXI_ACP 0 \
    CONFIG.PCW_USE_S_AXI_GP0 0 \
    CONFIG.PCW_USE_S_AXI_GP1 0 \
    CONFIG.PCW_USE_S_AXI_HP0 0 \
    CONFIG.PCW_USE_S_AXI_HP1 0 \
    CONFIG.PCW_USE_S_AXI_HP2 0 \
    CONFIG.PCW_USE_S_AXI_HP3 0 \
    CONFIG.PCW_USE_TRACE 0 \
    CONFIG.PCW_VALUE_SILVERSION 3 \
    CONFIG.PCW_WDT_PERIPHERAL_CLKSRC CPU_1X \
    CONFIG.PCW_WDT_PERIPHERAL_DIVISOR0 1 \
    CONFIG.PCW_WDT_PERIPHERAL_ENABLE 0 \
]
