#!/usr/bin/env bash
#-----------------------------------------------------------------------------
# reflash-sd.sh - prepare the TFTP payload for reflashing the microSD in-place.
#
#   ./linux/reflash-sd.sh <server-ip> [<board-ip> [<netmask>]]
#
#   <server-ip>  LAN IP of the PC running the TFTP server (as the board sees it)
#   <board-ip>   static IP for the board; omit to use DHCP
#
# Fills <repo>/build_tftp/ (point your TFTP server's root there):
#   sdcard.img    the image to write (from build-linux.sh)
#   reflash.scr   U-Boot script: tftp sdcard.img -> mmc 0, read back + compare,
#                 then boot the fresh card
#   u-boot, u-boot.dtb, ps7_init.tcl   for linux/reflash_sd.tcl (JTAG loader)
#
# Then per card: boot switch = JTAG, insert card, power on, run
#   linux\reflash_sd.bat          (Windows / Vitis xsct)
# or, from a U-Boot prompt on a board that already boots:
#   setenv autoload no; dhcp; tftpboot ${scriptaddr} <server-ip>:reflash.scr; source ${scriptaddr}
#
# Env: LINUX_BUILD_DIR (default <repo>/../zynqmini-linux), TFTP_DIR (default <repo>/build_tftp)
#-----------------------------------------------------------------------------
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${LINUX_BUILD_DIR:=$(dirname "$REPO")/zynqmini-linux}"
: "${TFTP_DIR:=$REPO/build_tftp}"
BR="$LINUX_BUILD_DIR/buildroot"
IMG="$BR/output/images"
UBDIR="$BR/output/build/uboot-custom"

die() { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: $0 <server-ip> [<board-ip> [<netmask>]]"
SERVER_IP=$1; BOARD_IP=${2:-}; NETMASK=${3:-255.255.255.0}
ipre='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
[[ $SERVER_IP =~ $ipre ]] || die "bad server IP: $SERVER_IP"
[ -z "$BOARD_IP" ] || [[ $BOARD_IP =~ $ipre ]] || die "bad board IP: $BOARD_IP"

for f in "$IMG/sdcard.img" "$IMG/u-boot" "$UBDIR/u-boot.dtb" "$LINUX_BUILD_DIR/xsa/ps7_init.tcl"; do
    [ -f "$f" ] || die "missing $f - run ./linux/build-linux.sh first"
done
MKIMAGE="$BR/output/host/bin/mkimage"
[ -x "$MKIMAGE" ] || MKIMAGE=$(command -v mkimage) || die "no mkimage found"

mkdir -p "$TFTP_DIR"
cp --sparse=always "$IMG/sdcard.img"             "$TFTP_DIR/sdcard.img"
cp "$IMG/u-boot"                                 "$TFTP_DIR/u-boot"
cp "$UBDIR/u-boot.dtb"                           "$TFTP_DIR/u-boot.dtb"
cp "$LINUX_BUILD_DIR/xsa/ps7_init.tcl"           "$TFTP_DIR/ps7_init.tcl"

if [ -n "$BOARD_IP" ]; then
    IP_SETUP="setenv ipaddr $BOARD_IP; setenv netmask $NETMASK; setenv rf_net 1"
    IP_DESC="static $BOARD_IP/$NETMASK"
else
    IP_SETUP="if dhcp; then setenv rf_net 1; else setenv rf_net 0; fi"
    IP_DESC="DHCP"
fi

# U-Boot hush script. Buffers: image @0x08000000, read-back @0x10000000
# (both clear of the DTB @0x100000, script @0x3000000, U-Boot @0x4000000 and
# U-Boot's relocated copy near the top of the 512 MB).
cat > "$TFTP_DIR/reflash.cmd" <<EOF
# reflash.cmd - generated by linux/reflash-sd.sh ($(date -Iseconds))
# TFTP server $SERVER_IP, board network: $IP_DESC
echo
echo "================ reflash microSD (mmc 0) from TFTP ================"
# distro boot must not re-run this script or try network boot afterwards
setenv bootcmd_jtag echo reflash: script already ran
setenv bootcmd_pxe  echo reflash: skipping pxe
setenv bootcmd_dhcp echo reflash: skipping dhcp
setenv autoload no
setenv serverip $SERVER_IP
setenv rf_buf 0x08000000
setenv rf_chk 0x10000000
setenv rf_ok 0
$IP_SETUP
if itest \${rf_net} -eq 0; then
  echo "reflash: ERROR network setup failed (no DHCP answer?)"
elif mmc dev 0; then
  echo "reflash: tftp \${serverip}:sdcard.img -> \${rf_buf}"
  if tftpboot \${rf_buf} sdcard.img; then
    if itest \${filesize} -gt 0x08000000; then
      echo "reflash: ERROR image is larger than 128 MB, will not fit the RAM buffers"
    else
      setexpr rf_blk \${filesize} + 1ff
      setexpr rf_blk \${rf_blk} / 200
      setexpr rf_wrd \${rf_blk} * 80
      echo "reflash: writing 0x\${rf_blk} blocks to mmc 0 ..."
      if mmc write \${rf_buf} 0 \${rf_blk}; then
        echo "reflash: reading back to verify ..."
        mmc read \${rf_chk} 0 \${rf_blk}
        if cmp.l \${rf_buf} \${rf_chk} \${rf_wrd}; then
          setenv rf_ok 1
        else
          echo "reflash: ERROR read-back does not match what was written"
        fi
      else
        echo "reflash: ERROR mmc write failed"
      fi
    fi
  else
    echo "reflash: ERROR tftp failed - server running? firewall? file in its root?"
  fi
else
  echo "reflash: ERROR no SD card in the slot"
fi
if itest \${rf_ok} -eq 1; then
  mmc rescan
  echo "================ reflash: DONE - booting the new card ================"
else
  echo "================ reflash: FAILED - staying at the U-Boot prompt ================"
  for t in mmc0 mmc1 qspi nand nor usb0 usb1; do setenv bootcmd_\${t} echo reflash: skipping \${t}; done
fi
EOF

"$MKIMAGE" -A arm -O linux -T script -C none -n "reflash microSD" \
    -d "$TFTP_DIR/reflash.cmd" "$TFTP_DIR/reflash.scr" >/dev/null

printf '\n\033[1;34m==> TFTP payload ready in %s\033[0m\n' "$TFTP_DIR"
ls -la "$TFTP_DIR"
WINPATH=$(wslpath -w "$TFTP_DIR" 2>/dev/null || true)
cat <<EOF

  1. Serve that directory over TFTP at $SERVER_IP (UDP 69):
       Windows: Tftpd64, "Current Directory" = ${WINPATH:-$TFTP_DIR}
       WSL:     tftpd-hpa with TFTP_DIRECTORY=$TFTP_DIR  (needs WSL mirrored networking)
  2. Per card: boot switch = JTAG, insert the card, power on, then on Windows:
       linux\\reflash_sd.bat
     Watch the serial console (115200 8N1). The board boots the new card when done.
  Board already at a U-Boot prompt instead:
       setenv autoload no; dhcp; tftpboot \${scriptaddr} $SERVER_IP:reflash.scr; source \${scriptaddr}
EOF
